### ISSUE TITLE
Translation of Ugame-docs into spanish

### ISSUE THREAD

**Issue by siersod-utopian** [python-ugame/ugame-docs#3]
Greetings Python-ugame Team!

I would like to help translating the documentation of Python-ugame into spanish language. In order to do so, I have a couple of questions.

Should I make a new branch called Spanish and do the translation from there? or how would it be more convenient to have this translation?

Thanks in advance for your answer.

**Comment by deshipu** [comment]
Hi, sorry for the delay, I didn't see this issue when it was reported.

I'm really not sure about how to handle translations right now. At the moment the "µGame team" consists of a single person, and not much spare cycles. The English documentation is a continuing work in progress, as I'm trying to add to it whenever I have some time. I really don't think I will be able to give the translations the attention that they deserve, and I think that outdated documentation is worse than documentation only in English.

Having said that, I have nothing against you forking this repository and working on a translation. If you let me know the URL for it, I can even add it as the translation to ReadTheDocs.
